### ISSUE TITLE
Create TTWG Charter 2019

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/tt-reqs#5]
Revise Charter to include in the scope and/or deliverables any documents that are needed to meet the agreed requirements.

**Comment by skynavga** [comment]
This is not a technical requirement, but a process requirement on the TTWG. Please move this issue to the ttwg repo.

**Comment by nigelmegitt** [comment]
OK, I put it here because it seems linked to the requirements related to it, but I take the point.
